// VideoDummyData.js
export const examplePosts = [
  {
    id: 0,
    thumbnail: `${process.env.PUBLIC_URL}/jumpstart-thumb.jpg`,
    title: `The Future of Jumpstarters`,
    creator: `Gryan Duminson`,
    date: `Dec 20, 2024`,
    views: 1200,
    likes: 60,
    comments: 9,
    duration: `13:30`,
    profilePic: `${process.env.PUBLIC_URL}/gryan-pfp.jpg`,
  },
  {
    id: 1,
    thumbnail: `${process.env.PUBLIC_URL}/jumpstart-thumb.jpg`,
    title: `Jumpstart Innovations Explained`,
    creator: `Gryan Duminson`,
    date: `Jan 5, 2025`,
    views: 980,
    likes: 48,
    comments: 7,
    duration: `14:10`,
    profilePic: `${process.env.PUBLIC_URL}/gryan-pfp.jpg`,
  },
  {
    id: 2,
    thumbnail: `${process.env.PUBLIC_URL}/jumpstart-thumb.jpg`,
    title: `How Jumpstarters Are Changing the Game`,
    creator: `Gryan Duminson`,
    date: `Feb 15, 2025`,
    views: 1500,
    likes: 80,
    comments: 15,
    duration: `12:45`,
    profilePic: `${process.env.PUBLIC_URL}/gryan-pfp.jpg`,
  },
  {
    id: 3,
    thumbnail: `${process.env.PUBLIC_URL}/jumpstart-thumb.jpg`,
    title: `Top 10 Jumpstarter Tips`,
    creator: `Gryan Duminson`,
    date: `Mar 10, 2025`,
    views: 700,
    likes: 35,
    comments: 4,
    duration: `11:50`,
    profilePic: `${process.env.PUBLIC_URL}/gryan-pfp.jpg`,
  },
  {
    id: 4,
    thumbnail: `${process.env.PUBLIC_URL}/jumpstart-thumb.jpg`,
    title: `Jumpstarters: What You Need to Know`,
    creator: `Gryan Duminson`,
    date: `Apr 1, 2025`,
    views: 1300,
    likes: 55,
    comments: 10,
    duration: `13:05`,
    profilePic: `${process.env.PUBLIC_URL}/gryan-pfp.jpg`,
  },
];
